name: composite

on:
    push:
      branches:
      - main

jobs:
  trial:
    name: job-name
    runs-on: ubuntu-latest
#     outputs:
#         temp_dir: ${{steps.dir.outputs.temp_dir}}
#         temp_file_suffix: ${{steps.filesuffix.outputs.temp_file}}
#         temp_file: ${{steps.file.outputs.temp_file}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: dir
        id: dir
        uses: almudena-alvarez/composite-workflow-simulator/.github/actions/create-temp-dir@main
        with:
            destination: "/home/runner/work/karate-simulator/karate-simulator"
            destfile: "/home/runner/work/karate-simulator/karate-simulator/text.txt"
      - name: dir echo
        id: direcho
        shell: bash
        run: |
            cd /home/runner/work/karate-simulator/karate-simulator
            ls -lart
            cat text.txt
#       - name: dir echo
#         id: direcho
#         shell: bash
#         run: echo ${{steps.dir.outputs.temp_dir}}
#       - name: filesuffix
#         id: filesuffix
#         uses: ./.github/actions/create-temp-file
#         with:
#           temp_dir: ${{steps.dir.outputs.temp_dir}}
#           name: "name"
#           file_type: "sql"
#       - name: filesuffix echo
#         id: filesuffixecho
#         shell: bash
#         run: echo ${{steps.filesuffix.outputs.temp_file}}
#       - name: file
#         id: file
#         uses: ./.github/actions/create-temp-file
#         with:
#           temp_dir: ${{steps.dir.outputs.temp_dir}}
#           name: "name"
#       - name: file echo
#         id: fileecho
#         shell: bash
#         run: echo ${{steps.file.outputs.temp_file}}
