name: Testing Flow

on:
  push:
    branches:
      - second-trial
  
jobs:
  call:
    uses: almudena-alvarez/composite-workflow-simulator/.github/workflows/composite-testing.yaml@main
    secrets:
      FIRST_SECRET: ${{ secrets.FIRST_SECRET }}
