name: Testing Flow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  call:
    uses: almudena-alvarez/composite-workflow-simulator/.github/workflows/postgres-checking.yaml@main
#     secrets:
#       FIRST_SECRET: ${{ secrets.FIRST_SECRET }}
