name: Testing Flow

on:
  workflow_dispatch:
  
jobs:
  call:
    uses: almudena-alvarez/composite-workflow-simulator/.github/workflows/checkvariable.yaml@main
    with:
      first_input: "lalala"
      array_input: "'jejeje','jfjfjf'"
      execute: true
